# Generated by Django 3.2.8 on 2021-10-13 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Entrez le prix du produit (sensible au millième)', max_digits=10, verbose_name='Prix du produit*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Entrez la description du produit (Max: 500 caractères)', max_length=500, null=True, verbose_name='Description du produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.CharField(help_text='Entrez le nom du produit (Max: 200 caractères)', max_length=200, verbose_name='Nom du produit*'),
        ),
    ]
