# Generated by Django 3.2.8 on 2021-10-14 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0005_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quatity',
            field=models.PositiveIntegerField(default=0, help_text='Entrez la quantité du produit', verbose_name='Quantité*'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Entrez le nom du produit (Max: 200 caractères)', max_length=200, null=True, verbose_name='Nom')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.category', verbose_name='Catégorie'),
        ),
    ]
