# Generated by Django 3.2.8 on 2021-10-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20211014_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer',
            field=models.CharField(help_text="Entrez le nom de l'acheteur (Max: 200 caractères)", max_length=200, null=True, verbose_name="Nom de l'acheteur"),
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.CharField(help_text='Entrez le nom du vendeur (Max: 200 caractères)', max_length=200, null=True, verbose_name='Nom du vendeur'),
        ),
    ]
